feat push implemented correctly [ci]

diff --git a/docker/dockerfile.api b/docker/dockerfile.api
--- a/docker/dockerfile.api
+++ b/docker/dockerfile.api
@@ -20,7 +20,7 @@ FROM alpine:latest
 
 RUN apk add --no-cache ca-certificates
 RUN apk add --no-cache ca-certificates curl dcron \
-    && printf '* * * * * i=0; while [ $i -lt 60 ]; do /usr/bin/curl -fsS http://localhost:8080/api/hello-world/hello || echo tick-fail >&2; sleep 1; i=$((i+1)); done\n' > /etc/crontabs/root \
+    && printf '* * * * * i=0; while [ $i -lt 60 ]; do /usr/bin/curl -fsS http://localhost:8080/api/check-notifications || echo tick-fail >&2; sleep 1; i=$((i+1)); done\n' > /etc/crontabs/root \
     && chmod 600 /etc/crontabs/root
 
 COPY --from=pocketbase-builder /pb /pb
